version: '3.10'

services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    restart: unless-stopped
    ports:
      - ${NGINX_SERVICE_PORT}:${NGINX_SERVICE_PORT}

  dashboard:
    build:
      context: .
      dockerfile: .docker/dashboard.dockerfile
    command: [ "wave", "run", "h2o_dashboard.dashboard" ]
    restart: unless-stopped

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - ${REDIS_SERVICE_PORT}:${REDIS_SERVICE_PORT}
    restart: unless-stopped

  okx_api:
    build:
      context: .
      dockerfile: .docker/bot.dockerfile
    ports:
      - ${OKX_API_SERVICE_PORT}:${OKX_API_SERVICE_PORT}
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - MODULE_PATH=${OKX_API_MODULE_PATH}
      - MODULE_NAME=${OKX_API_MODULE_NAME}
      - PORT=${OKX_API_SERVICE_PORT}
      - OKX_API_KEY=${OKX_API_KEY}
      - OKX_SECRET_KEY=${OKX_SECRET_KEY}
      - OKX_PASSPHRASE=${OKX_PASSPHRASE}

  okx_websockets:
    build:
      context: .
      dockerfile: .docker/bot.dockerfile
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - MODULE_PATH=${OKX_WS_MODULE_PATH}
      - MODULE_NAME=${OKX_WS_MODULE_NAME}
      - PORT=${OKX_WS_SERVICE_PORT}
      - OKX_API_KEY=${OKX_API_KEY}
      - OKX_SECRET_KEY=${OKX_SECRET_KEY}
      - OKX_PASSPHRASE=${OKX_PASSPHRASE}
