version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    restart: always
    ports:
      - ${NGINX_SERVICE_PORT}:${NGINX_SERVICE_PORT}

  dashboard:
    build:
      context: .
      dockerfile: .docker/dashboard.dockerfile
    command: ["wave", "run", "h2o_dashboard.dashboard"]
    restart: always
    volumes:
      - ./h2o_dashboard:/app

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - ${REDIS_SERVICE_PORT}:${REDIS_SERVICE_PORT}
    restart: always

  okx_api:
    build:
      context: .
      dockerfile: .docker/bot.dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload # Enable live reload
    ports:
      - ${OKX_API_SERVICE_PORT}:${OKX_API_SERVICE_PORT}
    restart: always
    depends_on:
      - redis
    volumes:
      - firebase_tools:/app
      - pyokx:/app
      - routers:/app
      - shared:/app
    environment:
      - MODULE_NAME=${OKX_API_MODULE_PATH}
      - VARIABLE_NAME=${OKX_API_MODULE_NAME}
      - PORT=${OKX_API_SERVICE_PORT}
      - OKX_API_KEY=${OKX_API_KEY}
      - OKX_SECRET_KEY=${OKX_SECRET_KEY}
      - OKX_PASSPHRASE=${OKX_PASSPHRASE}
